// Expression statements

// Certain expressions (such as x = 5) are used primarily for their side effects (in this case, to assign the value 5 to the variable x) rather than the value they produce.

// However, we mentioned above that expressions cannot be executed by themselves -- they must exist as part of a statement. Fortunately, it’s trivial to convert any expression into an equivalent statement. An expression statement is a statement that consists of an expression followed by a semicolon. When the expression statement is executed, the expression will be evaluated.
// Thus, we can take any expression (such as x = 5), and turn it into an expression statement (x = 5;) that will compile.
// When an expression is used in an expression statement, any result generated by the expression is discarded (because it is not used). For example, when the expression x = 5 evaluates, the return value of operator= is discarded. And that’s fine, because we just wanted to assign 5 to x anyway.


// Useless expression statements
// We can also make expression statements that compile but have no effect. For example, the expression statement (2 * 3;) is an expression statement whose expression evaluates to the result value of 6, which is then discarded. While syntactically valid, such expression statements are useless. Some compilers (such as gcc and Clang) will produce warnings if they can detect that an expression statement is useless.


// Subexpressions, full expressions, and compound expressions
// We occasionally need to talk about specific kinds of expressions. For this purpose, we will define some related terms.
// Consider the following expressions:
2               // 2 is a literal that evaluates to value 2
2 + 3           // 2 + 3 uses operator+ to evaluate to value 5
x = 4 + 5       // 4 + 5 evaluates to value 9, which is then assigned to variable x
// Simplifying a bit, a subexpression is an expression used as an operand. For example, the subexpressions of x = 4 + 5 are x and 4 + 5. The subexpressions of 4 + 5 are 4 and 5.
// A full expression is an expression that is not a subexpression. All three expressions above (2, 2 + 3, and x = 4 + 5) are full expressions.
// In casual language, a compound expression is an expression that contains two or more uses of operators. x = 4 + 5 is a compound expression because it contains two uses of operators (operator= and operator+). 2 and 2 + 3 are not compound expressions.
